"""Baseline: the schema as it stood when migrations were introduced.

Revision ID: 0001
Revises:
Create Date: 2026-09-24

The schema is written out here rather than imported from models.py: a
migration has to describe the database as it was at this point, not as the
models say it is today.

Databases created before migrations existed carry no version, so they run
this too. It therefore creates only the tables that are missing, and on tables
that exist adds only missing columns and indexes — what the old start-up
column patching did, so an old data directory upgrades in place.

That old patching added columns as nullable. Those are filled with their
default and made NOT NULL here, so every database at this revision matches the
models exactly and the next autogenerated migration starts from a clean diff.
"""

from __future__ import annotations

import json

import sqlalchemy as sa
from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None

meta = sa.MetaData()


def col(name, type_, *args, default=None, **kw):
    """A column, remembering the default an in-place ADD COLUMN should use."""
    kw.setdefault("nullable", False)
    return sa.Column(name, type_, *args, info={"default": default}, **kw)


sa.Table(
    "settings", meta,
    col("key", sa.String(64), primary_key=True),
    col("value", sa.Text(), default=""),
)

sa.Table(
    "servers", meta,
    col("id", sa.String(36), primary_key=True),
    col("name", sa.String(120)),
    col("address", sa.String(255)),
    col("auth_port", sa.Integer(), default=1812),
    col("acct_port", sa.Integer(), default=1813),
    col("secret_enc", sa.Text()),
    col("coa_enabled", sa.Boolean(), default=True),
    col("ad_hoc", sa.Boolean(), default=False),
    col("attributes_json", sa.JSON(), default={}),
    col("created", sa.DateTime()),
)

sa.Table(
    "certificates", meta,
    col("id", sa.String(36), primary_key=True),
    col("friendly_name", sa.String(160)),
    col("type", sa.String(32), index=True),
    col("content_pem", sa.Text()),
    col("key_pem_enc", sa.Text(), nullable=True),
    col("subject", sa.String(400), default=""),
    col("issuer", sa.String(400), default=""),
    col("serial", sa.String(80), default=""),
    col("thumbprint", sa.String(80), default=""),
    col("valid_from", sa.DateTime(), nullable=True),
    col("valid_to", sa.DateTime(), nullable=True),
    col("self_signed", sa.Boolean(), default=False),
    col("created", sa.DateTime()),
)

sa.Table(
    "jobs", meta,
    col("id", sa.String(36), primary_key=True),
    col("name", sa.String(120)),
    col("bulk", sa.String(120), index=True, default="none"),
    col("server_id", sa.String(36), sa.ForeignKey("servers.id")),
    col("status", sa.String(20), index=True, default="queued"),
    col("total", sa.Integer(), default=1),
    col("completed", sa.Integer(), default=0),
    col("failed", sa.Integer(), default=0),
    col("params_json", sa.JSON(), default={}),
    col("started", sa.DateTime()),
    col("finished", sa.DateTime(), nullable=True),
)

sa.Table(
    "bulk_operations", meta,
    col("id", sa.String(36), primary_key=True),
    col("kind", sa.String(20)),
    col("scope", sa.String(120), default=""),
    col("total", sa.Integer(), default=0),
    col("done", sa.Integer(), default=0),
    col("failed", sa.Integer(), default=0),
    col("status", sa.String(20), index=True, default="running"),
    col("note", sa.Text(), default=""),
    col("started", sa.DateTime()),
    col("finished", sa.DateTime(), nullable=True),
)

sa.Table(
    "sessions", meta,
    col("id", sa.String(36), primary_key=True),
    col("job_id", sa.String(36), sa.ForeignKey("jobs.id"), index=True),
    col("bulk", sa.String(120), index=True, default="none"),
    col("server_id", sa.String(36), index=True),
    col("mac", sa.String(64), default=""),
    col("ip", sa.String(64), default=""),
    col("username", sa.String(255), default=""),
    col("machine_name", sa.String(255), default=""),
    col("acct_session_id", sa.String(64), index=True, default=""),
    col("class_blob", sa.Text(), default=""),
    col("state_blob", sa.Text(), default=""),
    col("status", sa.String(20), index=True, default="error"),
    col("acct_status", sa.String(20), index=True, default=""),
    col("acct_session_time", sa.Integer(), default=0),
    col("reauth_count", sa.Integer(), default=0),
    col("expires_at", sa.DateTime(), nullable=True, index=True),
    col("lifetime_seconds", sa.Integer(), default=0),
    col("termination_action", sa.Integer(), default=0),
    col("duration", sa.Float(), default=0.0),
    col("started", sa.DateTime()),
    col("changed", sa.DateTime()),
    col("request_attrs_json", sa.JSON(), default={}),
    col("reply_attrs_json", sa.JSON(), default={}),
    col("legs_json", sa.JSON(), default=[]),
    col("log_json", sa.JSON(), default=[]),
)


def _sql_default(value):
    """A DDL DEFAULT clause for a Python scalar, or None."""
    if value is None:
        return None
    if isinstance(value, bool):
        return sa.text("1" if value else "0")
    if isinstance(value, (list, dict)):
        value = json.dumps(value)
    if isinstance(value, str):
        return sa.text("'" + value.replace("'", "''") + "'")
    return sa.text(repr(value))


def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing = set(inspector.get_table_names())

    for table in meta.sorted_tables:
        if table.name not in existing:
            table.create(bind)                 # with its indexes
            continue

        have = {c["name"] for c in inspector.get_columns(table.name)}
        for column in table.columns:
            if column.name in have:
                continue
            # Nullable, as the old patching added it: rows already in the table
            # have no value, and SQLite refuses NOT NULL without a default.
            op.add_column(table.name, sa.Column(
                column.name, column.type, nullable=True,
                server_default=_sql_default(column.info.get("default"))))

        indexed = {i["name"] for i in inspector.get_indexes(table.name)}
        for index in table.indexes:
            if index.name not in indexed:
                index.create(bind)

        _tighten_nullable(bind, table)


def _tighten_nullable(bind, table: sa.Table) -> None:
    """Make columns NOT NULL where the schema says so and the database does not.

    Only columns with a known default: NULLs are filled with it first. Anything
    without one is left nullable rather than guessed at.
    """
    nullable_now = {c["name"]: c["nullable"]
                    for c in sa.inspect(bind).get_columns(table.name)}
    loose = [c for c in table.columns
             if not c.nullable and nullable_now.get(c.name)
             and c.info.get("default") is not None]
    if not loose:
        return
    for column in loose:
        bind.execute(table.update().where(column.is_(None))
                     .values({column.name: column.info["default"]}))
    # SQLite cannot change NOT NULL in place: batch mode rebuilds the table,
    # carrying its rows and indexes across.
    with op.batch_alter_table(table.name) as batch:
        for column in loose:
            batch.alter_column(column.name, existing_type=column.type,
                               nullable=False)


def downgrade() -> None:
    for table in reversed(meta.sorted_tables):
        table.drop(op.get_bind())
